version: "3"
services:
  react-app:
    image: phd-client
    stdin_open: true
    ports: 
      - "3000:3000"
    environment:
      REACT_APP_BE_URL: "${REACT_APP_BE_URL}"
    networks:
      - mern-app
  api-server:
    image: phd-server
    ports:
      - "8080:8080"
    environment:
      MONGOURI: "${MONGOURI}"
      FRONTEND_PORT: "${FRONTEND_PORT}"
      JWTSECRET: "${JWTSECRET}"
      SENDGRID_API_KEY: "${SENDGRID_API_KEY}"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge